name: Release

on:
  create:
  push:
    tags:
      - "v[0-9].*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image
    steps:
      - name: 🚀 Release new version
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
